security:
    # Password hashing configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Role hierarchy
    role_hierarchy:
        ROLE_ADMIN: [ ROLE_MODERATOR ]
        ROLE_MODERATOR: [ ROLE_USER ]
        ROLE_USER: [ ]


    # User providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls
    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login # Matches the route name in LoginController
                check_path: app_login # Matches the route name in LoginController
                username_parameter: email # Match the form field name
                password_parameter: password # Match the form field name
                default_target_path: /
                enable_csrf: true
                csrf_token_id: authenticate

            logout:
                path: app_logout
                target: /

            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 604800 # a week
                path: /

    # Access control rules
    access_control:
        - { path: ^/categories, roles: PUBLIC_ACCESS  }
        - { path: ^/adverts, roles: PUBLIC_ACCESS  }
        - { path: ^/adverts/view, roles: PUBLIC_ACCESS }
        - { path: ^/advert/delete, roles: ROLE_MODERATOR }
        - { path: ^/advert/create, roles: ROLE_USER }
        - { path: ^/advert/edit, roles: ROLE_USER }
        - { path: ^/category/create, roles: ROLE_ADMIN }
        - { path: ^/admin/users, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

